export const sourceStudentDisplayNames = {
  E001: "Andrea López Ramírez",
  E002: "Diego Hernández Soto",
  E003: "Carlos Méndez Ruiz",
  E004: "Valeria Navarro Díaz",
  E005: "José Manuel Torres Vega",
  E006: "Sofía Castillo Pérez",
  E007: "Luis Fernando Ortega Cruz",
  E008: "Miguel Ángel Romero Salas",
  E009: "Emiliano Vargas León",
  E010: "Ximena Padilla Ríos",
  E011: "Daniela Guerrero Flores",
  E012: "Regina Ponce Silva",
  E013: "Fernanda Núñez Mora",
  E014: "Alonso Cárdenas Peña",
  E015: "Natalia Herrera Campos",
  E016: "Sebastián Lozano Gil",
  E017: "Rodrigo Chávez Ibarra",
  E018: "Eduardo Fuentes Reyes",
  E019: "Ricardo Domínguez Lara",
  E020: "Gael Cabrera Soto",
  E021: "Mariana Escobar Vela",
  E022: "Santiago Beltrán Rojas",
  E023: "Renata Pineda Ortiz",
  E024: "Camila Serrano Luna",
  E025: "Ángel Molina Trejo",
  E026: "Paulina Acosta Mejía",
  E027: "Iván Solís Aguirre",
  E028: "Mateo Vázquez Castro",
  E029: "Lucía Barrera Cortés",
  E030: "Jimena Vera Salgado",
  E031: "Héctor Montaño Ruiz",
  E032: "Zoe Delgado Peña",
  E033: "Alejandra Téllez Franco",
  E034: "Mía Contreras Rosales",
  E035: "Bruno Miranda Flores",
  E036: "Elisa Zamora Nieto",
  E037: "Aitana Rosas Mejía",
  E038: "Karla Valencia Márquez",
  E039: "Nicolás Andrade Vera",
  E040: "Óscar Medina Pardo",
  E041: "Javier Rangel Sierra",
  E042: "Abril Tapia Lozano",
  E043: "Tomás Quintana Reyes",
  E044: "Montserrat Figueroa Solano",
  E045: "Paula Enríquez Silva",
  E046: "Diego Alejandro Luján Cruz",
  E047: "Marco Antonio Ceballos Ortiz",
  E048: "Isaac Villalobos Peña",
  E049: "Ana Paula Treviño Salas",
  E050: "Francisco Gallegos Mora",
  E051: "Adrián Camacho Ruiz",
  E052: "Leonardo Chávez Luna",
  E053: "Victoria Ochoa Serrano",
  E054: "Emilio Velasco Duarte",
  E055: "Maximiliano Castañeda León",
  E056: "Andrea Sofía Murillo Paz",
  E057: "José Pablo Mena Ortiz",
  E058: "Danna Lizbeth Arias Flores",
  E059: "Samanta Rubio Cordero",
  E060: "Fátima Rivas Calderón",
  E061: "Alan Salcedo Vega",
  E062: "Cristian Palacios Ibarra",
  E063: "Valentina Bonilla Cruz",
  E064: "Bruno Esteban Alvarado Núñez",
  E065: "María José Zambrano Gil",
  E066: "Paola Sandoval Cárdenas",
  E067: "Gerardo Cifuentes Rocha",
  E068: "Nicole Becerra Soto",
  E069: "Aarón Castañón Pérez",
  E070: "Iker Valencia Toro",
  E071: "Patricio Aguado Mora",
  E072: "Renata del Río Campos"
} as const;

export const sourceTeacherDisplayNames = {
  D01: "María Fernanda Aguirre Soto",
  D02: "Ricardo Salinas Pérez",
  D03: "Laura Elena Pacheco Ruiz",
  D04: "Adriana Cárdenas Robles",
  D05: "Javier Morales Vega",
  D06: "Mariana Torres Villaseñor",
  D07: "Carlos Alberto Navarro Cruz",
  D08: "Sergio Ibarra Ríos"
} as const;

export const sourceStudentRegistry = [
  { id: "E001", semester: "3", group: "3B", age: "15", sex: "Mujer", barrier: "Me cuesta identificar qué tarea quedó exactamente", preferredMaterial: "Pasos numerados", comment: "Si tuviera glosario sería más fácil cuando salen palabras difíciles." },
  { id: "E002", semester: "2", group: "2B", age: "16", sex: "Hombre", barrier: "Entiendo mejor cuando tengo un resumen breve o una lista de pasos", preferredMaterial: "Resumen breve", comment: "Si me llegara un resumen al final sí lo revisaría en la tarde." },
  { id: "E003", semester: "3", group: "3B", age: "16", sex: "Hombre", barrier: "Entiendo mejor cuando tengo un resumen breve o una lista de pasos", preferredMaterial: "Recordatorio de tarea", comment: "Me ayudaría mucho que la tarea quedara en pasos claros." },
  { id: "E004", semester: "3", group: "3B", age: "16", sex: "Mujer", barrier: "No siempre organizo bien mis apuntes después de clase", preferredMaterial: "Esquema visual", comment: "A veces sí entiendo en clase, pero después ya no recuerdo qué hacer." },
  { id: "E005", semester: "1", group: "1B", age: "16", sex: "Hombre", barrier: "Entiendo mejor cuando tengo un resumen breve o una lista de pasos", preferredMaterial: "Glosario sencillo", comment: "Si me llegara un resumen al final sí lo revisaría en la tarde." },
  { id: "E006", semester: "2", group: "2A", age: "17", sex: "Mujer", barrier: "Cuando la clase es muy rápida me quedo con dudas para repasar", preferredMaterial: "Esquema visual", comment: "Si me llegara un resumen al final sí lo revisaría en la tarde." },
  { id: "E007", semester: "1", group: "1A", age: "16", sex: "Hombre", barrier: "Entiendo mejor cuando tengo un resumen breve o una lista de pasos", preferredMaterial: "Pasos numerados", comment: "Si tuviera glosario sería más fácil cuando salen palabras difíciles." },
  { id: "E008", semester: "2", group: "2A", age: "17", sex: "Hombre", barrier: "A veces escucho la explicación pero se me van algunos pasos", preferredMaterial: "Recordatorio de tarea", comment: "Creo que serviría para todo el grupo, no solo para algunos compañeros." },
  { id: "E009", semester: "2", group: "2B", age: "16", sex: "Hombre", barrier: "Cuando la clase es muy rápida me quedo con dudas para repasar", preferredMaterial: "Esquema visual", comment: "Me ayudaría mucho que la tarea quedara en pasos claros." },
  { id: "E010", semester: "1", group: "1A", age: "17", sex: "Mujer", barrier: "Entiendo mejor cuando tengo un resumen breve o una lista de pasos", preferredMaterial: "Recordatorio de tarea", comment: "Si tuviera glosario sería más fácil cuando salen palabras difíciles." },
  { id: "E011", semester: "3", group: "3B", age: "17", sex: "Mujer", barrier: "No siempre organizo bien mis apuntes después de clase", preferredMaterial: "Pasos numerados", comment: "Creo que serviría para todo el grupo, no solo para algunos compañeros." },
  { id: "E012", semester: "3", group: "3A", age: "15", sex: "Mujer", barrier: "A veces escucho la explicación pero se me van algunos pasos", preferredMaterial: "Recordatorio de tarea", comment: "A veces sí entiendo en clase, pero después ya no recuerdo qué hacer." },
  { id: "E013", semester: "1", group: "1B", age: "16", sex: "Mujer", barrier: "Cuando la clase es muy rápida me quedo con dudas para repasar", preferredMaterial: "Glosario sencillo", comment: "Creo que serviría para todo el grupo, no solo para algunos compañeros." },
  { id: "E014", semester: "1", group: "1B", age: "18", sex: "Hombre", barrier: "Me cuesta identificar qué tarea quedó exactamente", preferredMaterial: "Pasos numerados", comment: "Creo que serviría para todo el grupo, no solo para algunos compañeros." },
  { id: "E015", semester: "1", group: "1A", age: "16", sex: "Mujer", barrier: "A veces escucho la explicación pero se me van algunos pasos", preferredMaterial: "Esquema visual", comment: "Si me llegara un resumen al final sí lo revisaría en la tarde." },
  { id: "E016", semester: "1", group: "1B", age: "18", sex: "Hombre", barrier: "Me confundo si la indicación es larga o tiene varias partes", preferredMaterial: "Glosario sencillo", comment: "A veces sí entiendo en clase, pero después ya no recuerdo qué hacer." },
  { id: "E017", semester: "1", group: "1A", age: "16", sex: "Hombre", barrier: "No siempre organizo bien mis apuntes después de clase", preferredMaterial: "Pasos numerados", comment: "A veces sí entiendo en clase, pero después ya no recuerdo qué hacer." },
  { id: "E018", semester: "1", group: "1A", age: "18", sex: "Hombre", barrier: "Cuando la clase es muy rápida me quedo con dudas para repasar", preferredMaterial: "Recordatorio de tarea", comment: "Me ayudaría mucho que la tarea quedara en pasos claros." },
  { id: "E019", semester: "1", group: "1B", age: "17", sex: "Hombre", barrier: "Me cuesta identificar qué tarea quedó exactamente", preferredMaterial: "Glosario sencillo", comment: "Creo que serviría para todo el grupo, no solo para algunos compañeros." },
  { id: "E020", semester: "3", group: "3B", age: "18", sex: "Hombre", barrier: "Entiendo mejor cuando tengo un resumen breve o una lista de pasos", preferredMaterial: "Resumen breve", comment: "Si me llegara un resumen al final sí lo revisaría en la tarde." },
  { id: "E021", semester: "2", group: "2B", age: "16", sex: "Mujer", barrier: "Me confundo si la indicación es larga o tiene varias partes", preferredMaterial: "Pasos numerados", comment: "Si tuviera glosario sería más fácil cuando salen palabras difíciles." },
  { id: "E022", semester: "2", group: "2B", age: "17", sex: "Hombre", barrier: "Cuando la clase es muy rápida me quedo con dudas para repasar", preferredMaterial: "Recordatorio de tarea", comment: "Preferiría algo corto, claro y con ejemplos." },
  { id: "E023", semester: "2", group: "2B", age: "15", sex: "Mujer", barrier: "Me confundo si la indicación es larga o tiene varias partes", preferredMaterial: "Pasos numerados", comment: "A veces sí entiendo en clase, pero después ya no recuerdo qué hacer." },
  { id: "E024", semester: "2", group: "2B", age: "17", sex: "Mujer", barrier: "Me confundo si la indicación es larga o tiene varias partes", preferredMaterial: "Glosario sencillo", comment: "A veces sí entiendo en clase, pero después ya no recuerdo qué hacer." },
  { id: "E025", semester: "2", group: "2B", age: "16", sex: "Hombre", barrier: "A veces escucho la explicación pero se me van algunos pasos", preferredMaterial: "Esquema visual", comment: "Si tuviera glosario sería más fácil cuando salen palabras difíciles." },
  { id: "E026", semester: "2", group: "2A", age: "16", sex: "Mujer", barrier: "Cuando la clase es muy rápida me quedo con dudas para repasar", preferredMaterial: "Recordatorio de tarea", comment: "Si me llegara un resumen al final sí lo revisaría en la tarde." },
  { id: "E027", semester: "3", group: "3A", age: "15", sex: "Hombre", barrier: "Me confundo si la indicación es larga o tiene varias partes", preferredMaterial: "Esquema visual", comment: "Preferiría algo corto, claro y con ejemplos." },
  { id: "E028", semester: "3", group: "3B", age: "17", sex: "Hombre", barrier: "No siempre organizo bien mis apuntes después de clase", preferredMaterial: "Resumen breve", comment: "Creo que serviría para todo el grupo, no solo para algunos compañeros." },
  { id: "E029", semester: "1", group: "1B", age: "15", sex: "Mujer", barrier: "Entiendo mejor cuando tengo un resumen breve o una lista de pasos", preferredMaterial: "Esquema visual", comment: "A veces sí entiendo en clase, pero después ya no recuerdo qué hacer." },
  { id: "E030", semester: "2", group: "2A", age: "16", sex: "Mujer", barrier: "No siempre organizo bien mis apuntes después de clase", preferredMaterial: "Pasos numerados", comment: "A veces sí entiendo en clase, pero después ya no recuerdo qué hacer." },
  { id: "E031", semester: "1", group: "1A", age: "15", sex: "Hombre", barrier: "A veces escucho la explicación pero se me van algunos pasos", preferredMaterial: "Recordatorio de tarea", comment: "A veces sí entiendo en clase, pero después ya no recuerdo qué hacer." },
  { id: "E032", semester: "1", group: "1A", age: "16", sex: "Mujer", barrier: "Me cuesta identificar qué tarea quedó exactamente", preferredMaterial: "Pasos numerados", comment: "Me ayudaría mucho que la tarea quedara en pasos claros." },
  { id: "E033", semester: "1", group: "1B", age: "17", sex: "Mujer", barrier: "A veces escucho la explicación pero se me van algunos pasos", preferredMaterial: "Glosario sencillo", comment: "Me ayudaría mucho que la tarea quedara en pasos claros." },
  { id: "E034", semester: "1", group: "1A", age: "15", sex: "Mujer", barrier: "Entiendo mejor cuando tengo un resumen breve o una lista de pasos", preferredMaterial: "Recordatorio de tarea", comment: "Creo que serviría para todo el grupo, no solo para algunos compañeros." },
  { id: "E035", semester: "1", group: "1A", age: "18", sex: "Hombre", barrier: "Entiendo mejor cuando tengo un resumen breve o una lista de pasos", preferredMaterial: "Esquema visual", comment: "Creo que serviría para todo el grupo, no solo para algunos compañeros." },
  { id: "E036", semester: "1", group: "1A", age: "17", sex: "Mujer", barrier: "Me confundo si la indicación es larga o tiene varias partes", preferredMaterial: "Esquema visual", comment: "Si me llegara un resumen al final sí lo revisaría en la tarde." },
  { id: "E037", semester: "1", group: "1A", age: "18", sex: "Mujer", barrier: "A veces escucho la explicación pero se me van algunos pasos", preferredMaterial: "Esquema visual", comment: "Me ayudaría mucho que la tarea quedara en pasos claros." },
  { id: "E038", semester: "3", group: "3A", age: "17", sex: "Mujer", barrier: "Me confundo si la indicación es larga o tiene varias partes", preferredMaterial: "Glosario sencillo", comment: "Me ayudaría mucho que la tarea quedara en pasos claros." },
  { id: "E039", semester: "3", group: "3B", age: "16", sex: "Hombre", barrier: "No siempre organizo bien mis apuntes después de clase", preferredMaterial: "Esquema visual", comment: "Si me llegara un resumen al final sí lo revisaría en la tarde." },
  { id: "E040", semester: "3", group: "3B", age: "16", sex: "Hombre", barrier: "A veces escucho la explicación pero se me van algunos pasos", preferredMaterial: "Glosario sencillo", comment: "Me ayudaría mucho que la tarea quedara en pasos claros." },
  { id: "E041", semester: "3", group: "3B", age: "15", sex: "Hombre", barrier: "Me confundo si la indicación es larga o tiene varias partes", preferredMaterial: "Recordatorio de tarea", comment: "Si tuviera glosario sería más fácil cuando salen palabras difíciles." },
  { id: "E042", semester: "1", group: "1B", age: "17", sex: "Mujer", barrier: "Me confundo si la indicación es larga o tiene varias partes", preferredMaterial: "Resumen breve", comment: "Me ayudaría mucho que la tarea quedara en pasos claros." },
  { id: "E043", semester: "2", group: "2B", age: "17", sex: "Hombre", barrier: "Entiendo mejor cuando tengo un resumen breve o una lista de pasos", preferredMaterial: "Pasos numerados", comment: "Creo que serviría para todo el grupo, no solo para algunos compañeros." },
  { id: "E044", semester: "2", group: "2A", age: "18", sex: "Mujer", barrier: "Cuando la clase es muy rápida me quedo con dudas para repasar", preferredMaterial: "Esquema visual", comment: "A veces sí entiendo en clase, pero después ya no recuerdo qué hacer." },
  { id: "E045", semester: "3", group: "3B", age: "16", sex: "Mujer", barrier: "Entiendo mejor cuando tengo un resumen breve o una lista de pasos", preferredMaterial: "Glosario sencillo", comment: "Si me llegara un resumen al final sí lo revisaría en la tarde." },
  { id: "E046", semester: "3", group: "3B", age: "16", sex: "Hombre", barrier: "Me confundo si la indicación es larga o tiene varias partes", preferredMaterial: "Glosario sencillo", comment: "Si tuviera glosario sería más fácil cuando salen palabras difíciles." },
  { id: "E047", semester: "3", group: "3B", age: "18", sex: "Hombre", barrier: "Me cuesta identificar qué tarea quedó exactamente", preferredMaterial: "Esquema visual", comment: "A veces sí entiendo en clase, pero después ya no recuerdo qué hacer." },
  { id: "E048", semester: "1", group: "1B", age: "15", sex: "Hombre", barrier: "Cuando la clase es muy rápida me quedo con dudas para repasar", preferredMaterial: "Pasos numerados", comment: "Me ayudaría mucho que la tarea quedara en pasos claros." },
  { id: "E049", semester: "3", group: "3A", age: "16", sex: "Mujer", barrier: "No siempre organizo bien mis apuntes después de clase", preferredMaterial: "Resumen breve", comment: "Si tuviera glosario sería más fácil cuando salen palabras difíciles." },
  { id: "E050", semester: "3", group: "3B", age: "17", sex: "Hombre", barrier: "No siempre organizo bien mis apuntes después de clase", preferredMaterial: "Glosario sencillo", comment: "Preferiría algo corto, claro y con ejemplos." },
  { id: "E051", semester: "3", group: "3A", age: "17", sex: "Hombre", barrier: "Me confundo si la indicación es larga o tiene varias partes", preferredMaterial: "Resumen breve", comment: "Si me llegara un resumen al final sí lo revisaría en la tarde." },
  { id: "E052", semester: "1", group: "1A", age: "15", sex: "Hombre", barrier: "A veces escucho la explicación pero se me van algunos pasos", preferredMaterial: "Pasos numerados", comment: "Si tuviera glosario sería más fácil cuando salen palabras difíciles." },
  { id: "E053", semester: "2", group: "2B", age: "16", sex: "Mujer", barrier: "Cuando la clase es muy rápida me quedo con dudas para repasar", preferredMaterial: "Glosario sencillo", comment: "Si me llegara un resumen al final sí lo revisaría en la tarde." },
  { id: "E054", semester: "1", group: "1B", age: "16", sex: "Hombre", barrier: "Me confundo si la indicación es larga o tiene varias partes", preferredMaterial: "Esquema visual", comment: "Preferiría algo corto, claro y con ejemplos." },
  { id: "E055", semester: "3", group: "3A", age: "17", sex: "Hombre", barrier: "Me cuesta identificar qué tarea quedó exactamente", preferredMaterial: "Esquema visual", comment: "Si tuviera glosario sería más fácil cuando salen palabras difíciles." },
  { id: "E056", semester: "2", group: "2B", age: "16", sex: "Mujer", barrier: "Cuando la clase es muy rápida me quedo con dudas para repasar", preferredMaterial: "Pasos numerados", comment: "Creo que serviría para todo el grupo, no solo para algunos compañeros." },
  { id: "E057", semester: "2", group: "2B", age: "18", sex: "Hombre", barrier: "A veces escucho la explicación pero se me van algunos pasos", preferredMaterial: "Pasos numerados", comment: "Si me llegara un resumen al final sí lo revisaría en la tarde." },
  { id: "E058", semester: "1", group: "1B", age: "16", sex: "Mujer", barrier: "Me confundo si la indicación es larga o tiene varias partes", preferredMaterial: "Esquema visual", comment: "Si tuviera glosario sería más fácil cuando salen palabras difíciles." },
  { id: "E059", semester: "2", group: "2A", age: "16", sex: "Mujer", barrier: "A veces escucho la explicación pero se me van algunos pasos", preferredMaterial: "Glosario sencillo", comment: "Creo que serviría para todo el grupo, no solo para algunos compañeros." },
  { id: "E060", semester: "2", group: "2B", age: "17", sex: "Mujer", barrier: "Me cuesta identificar qué tarea quedó exactamente", preferredMaterial: "Glosario sencillo", comment: "Si me llegara un resumen al final sí lo revisaría en la tarde." },
  { id: "E061", semester: "2", group: "2A", age: "15", sex: "Hombre", barrier: "A veces escucho la explicación pero se me van algunos pasos", preferredMaterial: "Recordatorio de tarea", comment: "Si me llegara un resumen al final sí lo revisaría en la tarde." },
  { id: "E062", semester: "3", group: "3B", age: "18", sex: "Hombre", barrier: "No siempre organizo bien mis apuntes después de clase", preferredMaterial: "Pasos numerados", comment: "Creo que serviría para todo el grupo, no solo para algunos compañeros." },
  { id: "E063", semester: "2", group: "2B", age: "16", sex: "Mujer", barrier: "A veces escucho la explicación pero se me van algunos pasos", preferredMaterial: "Glosario sencillo", comment: "Si tuviera glosario sería más fácil cuando salen palabras difíciles." },
  { id: "E064", semester: "3", group: "3A", age: "17", sex: "Hombre", barrier: "Me confundo si la indicación es larga o tiene varias partes", preferredMaterial: "Recordatorio de tarea", comment: "Me ayudaría mucho que la tarea quedara en pasos claros." },
  { id: "E065", semester: "2", group: "2B", age: "15", sex: "Mujer", barrier: "A veces escucho la explicación pero se me van algunos pasos", preferredMaterial: "Esquema visual", comment: "Preferiría algo corto, claro y con ejemplos." },
  { id: "E066", semester: "3", group: "3A", age: "15", sex: "Mujer", barrier: "No siempre organizo bien mis apuntes después de clase", preferredMaterial: "Pasos numerados", comment: "Si tuviera glosario sería más fácil cuando salen palabras difíciles." },
  { id: "E067", semester: "1", group: "1B", age: "16", sex: "Hombre", barrier: "Cuando la clase es muy rápida me quedo con dudas para repasar", preferredMaterial: "Resumen breve", comment: "A veces sí entiendo en clase, pero después ya no recuerdo qué hacer." },
  { id: "E068", semester: "1", group: "1B", age: "18", sex: "Mujer", barrier: "A veces escucho la explicación pero se me van algunos pasos", preferredMaterial: "Resumen breve", comment: "A veces sí entiendo en clase, pero después ya no recuerdo qué hacer." },
  { id: "E069", semester: "2", group: "2A", age: "17", sex: "Hombre", barrier: "Me confundo si la indicación es larga o tiene varias partes", preferredMaterial: "Glosario sencillo", comment: "Creo que serviría para todo el grupo, no solo para algunos compañeros." },
  { id: "E070", semester: "2", group: "2A", age: "15", sex: "Hombre", barrier: "Me cuesta identificar qué tarea quedó exactamente", preferredMaterial: "Resumen breve", comment: "Si tuviera glosario sería más fácil cuando salen palabras difíciles." },
  { id: "E071", semester: "3", group: "3B", age: "17", sex: "Hombre", barrier: "Me cuesta identificar qué tarea quedó exactamente", preferredMaterial: "Recordatorio de tarea", comment: "Me ayudaría mucho que la tarea quedara en pasos claros." },
  { id: "E072", semester: "3", group: "3A", age: "16", sex: "Hombre", barrier: "A veces escucho la explicación pero se me van algunos pasos", preferredMaterial: "Esquema visual", comment: "Si me llegara un resumen al final sí lo revisaría en la tarde." }
] as const;

export const sourceTeacherDirectory = [
  { id: "D01", roleLabel: "Docente", area: "Matemáticas", priorityOutput: "Resumen + pasos", comment: "Los alumnos suelen pedir que se repitan las consignas cuando la actividad tiene varias partes." },
  { id: "D02", roleLabel: "Docente", area: "Comunicación", priorityOutput: "Esquema visual", comment: "Un resumen breve por clase ayudaría a cerrar dudas y a dejar la tarea más clara." },
  { id: "D03", roleLabel: "Tutoría", area: "Tutoría", priorityOutput: "Esquema visual", comment: "En grupos diversos serviría mucho contar con una versión más organizada de la explicación." },
  { id: "D04", roleLabel: "Orientación", area: "Orientación", priorityOutput: "Glosario + resumen", comment: "No se trata de reemplazar al docente, sino de dejar un apoyo de repaso después de clase." },
  { id: "D05", roleLabel: "Coordinación", area: "Coordinación Académica", priorityOutput: "Glosario + resumen", comment: "La herramienta sería útil sobre todo cuando hay estudiantes que requieren mayor claridad o estructura." },
  { id: "D06", roleLabel: "Docente", area: "Biología", priorityOutput: "Pasos numerados", comment: "Veo viable usarla si el formato de salida es breve, claro y fácil de enviar." },
  { id: "D07", roleLabel: "Docente", area: "Inglés", priorityOutput: "Resumen + pasos", comment: "Los pasos numerados y el recordatorio de tarea serían de lo más valioso." },
  { id: "D08", roleLabel: "Prefectura", area: "Prefectura", priorityOutput: "Pasos numerados", comment: "Ayudaría a todo el grupo, no solo a quienes tienen apoyos identificados." }
] as const;

export const sourceAccessibilityContext = [
  { category: "TDA / TDAH", count: "8", observedNeed: "Dificultad para sostener atención, organizar pasos e inhibir distractores.", suggestedSupport: "Pasos numerados, recordatorio de tarea, resumen breve y estructura clara." },
  { category: "TEA nivel 1", count: "2", observedNeed: "Necesidad de mayor anticipación, claridad de consignas y menor ambigüedad.", suggestedSupport: "Secuencia clara, lenguaje directo y apoyo visual simple." },
  { category: "Alteración del lenguaje / comprensión", count: "2", observedNeed: "Necesidad de lenguaje sencillo, glosario y reformulación.", suggestedSupport: "Versión simplificada, glosario y resumen accesible." },
  { category: "Procesamiento sensorial", count: "1", observedNeed: "Sobrecarga por estímulos o saturación de información.", suggestedSupport: "Formato limpio, breve y poco saturado visualmente." },
  { category: "Ansiedad / pánico / regulación emocional", count: "3", observedNeed: "Confusión o saturación frente a varias consignas o presión de tiempo.", suggestedSupport: "Recordatorio claro, pasos concretos y apoyo postclase para reducir incertidumbre." },
  { category: "Otras condiciones de salud o seguimiento", count: "1", observedNeed: "Requieren claridad y facilidad de consulta posterior.", suggestedSupport: "Material breve y ordenado disponible para repaso posterior." }
] as const;
